/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LineGraph */

#ifndef _Included_LineGraph
#define _Included_LineGraph
#ifdef __cplusplus
extern "C" {
#endif
#undef LineGraph_FOCUS_TRAVERSABLE_UNKNOWN
#define LineGraph_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef LineGraph_FOCUS_TRAVERSABLE_DEFAULT
#define LineGraph_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef LineGraph_FOCUS_TRAVERSABLE_SET
#define LineGraph_FOCUS_TRAVERSABLE_SET 2L
/* Inaccessible static: focusTraversalKeyPropertyNames */
/* Inaccessible static: LOCK */
/* Inaccessible static: dbg */
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef LineGraph_TOP_ALIGNMENT
#define LineGraph_TOP_ALIGNMENT 0.0f
#undef LineGraph_CENTER_ALIGNMENT
#define LineGraph_CENTER_ALIGNMENT 0.5f
#undef LineGraph_BOTTOM_ALIGNMENT
#define LineGraph_BOTTOM_ALIGNMENT 1.0f
#undef LineGraph_LEFT_ALIGNMENT
#define LineGraph_LEFT_ALIGNMENT 0.0f
#undef LineGraph_RIGHT_ALIGNMENT
#define LineGraph_RIGHT_ALIGNMENT 1.0f
#undef LineGraph_serialVersionUID
#define LineGraph_serialVersionUID -7644114512714619750LL
/* Inaccessible static: metrics */
/* Inaccessible static: class_00024java_00024awt_00024Component */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ComponentListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024FocusListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyBoundsListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024KeyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseMotionListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseWheelListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024InputMethodListener */
/* Inaccessible static: class_00024java_00024beans_00024PropertyChangeListener */
#undef LineGraph_serialVersionUID
#define LineGraph_serialVersionUID 4613797578919906343LL
/* Inaccessible static: dbg */
#undef LineGraph_INCLUDE_SELF
#define LineGraph_INCLUDE_SELF 1L
#undef LineGraph_SEARCH_HEAVYWEIGHTS
#define LineGraph_SEARCH_HEAVYWEIGHTS 1L
/* Inaccessible static: class_00024java_00024awt_00024Container */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ContainerListener */
/* Inaccessible static: readObjectCallbacks */
/* Inaccessible static: managingFocusForwardTraversalKeys */
/* Inaccessible static: managingFocusBackwardTraversalKeys */
/* Inaccessible static: suppressDropSupport */
/* Inaccessible static: checkedSuppressDropSupport */
#undef LineGraph_NOT_OBSCURED
#define LineGraph_NOT_OBSCURED 0L
#undef LineGraph_PARTIALLY_OBSCURED
#define LineGraph_PARTIALLY_OBSCURED 1L
#undef LineGraph_COMPLETELY_OBSCURED
#define LineGraph_COMPLETELY_OBSCURED 2L
#undef LineGraph_WHEN_FOCUSED
#define LineGraph_WHEN_FOCUSED 0L
#undef LineGraph_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
#define LineGraph_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT 1L
#undef LineGraph_WHEN_IN_FOCUSED_WINDOW
#define LineGraph_WHEN_IN_FOCUSED_WINDOW 2L
#undef LineGraph_UNDEFINED_CONDITION
#define LineGraph_UNDEFINED_CONDITION -1L
#undef LineGraph_IS_DOUBLE_BUFFERED
#define LineGraph_IS_DOUBLE_BUFFERED 0L
#undef LineGraph_ANCESTOR_USING_BUFFER
#define LineGraph_ANCESTOR_USING_BUFFER 1L
#undef LineGraph_IS_PAINTING_TILE
#define LineGraph_IS_PAINTING_TILE 2L
#undef LineGraph_IS_OPAQUE
#define LineGraph_IS_OPAQUE 3L
#undef LineGraph_KEY_EVENTS_ENABLED
#define LineGraph_KEY_EVENTS_ENABLED 4L
#undef LineGraph_FOCUS_INPUTMAP_CREATED
#define LineGraph_FOCUS_INPUTMAP_CREATED 5L
#undef LineGraph_ANCESTOR_INPUTMAP_CREATED
#define LineGraph_ANCESTOR_INPUTMAP_CREATED 6L
#undef LineGraph_WIF_INPUTMAP_CREATED
#define LineGraph_WIF_INPUTMAP_CREATED 7L
#undef LineGraph_ACTIONMAP_CREATED
#define LineGraph_ACTIONMAP_CREATED 8L
#undef LineGraph_CREATED_DOUBLE_BUFFER
#define LineGraph_CREATED_DOUBLE_BUFFER 9L
#undef LineGraph_CREATED_VOLATILE_DOUBLE_BUFFER
#define LineGraph_CREATED_VOLATILE_DOUBLE_BUFFER 10L
#undef LineGraph_IS_PRINTING
#define LineGraph_IS_PRINTING 11L
#undef LineGraph_IS_PRINTING_ALL
#define LineGraph_IS_PRINTING_ALL 12L
#undef LineGraph_IS_REPAINTING
#define LineGraph_IS_REPAINTING 13L
#undef LineGraph_WRITE_OBJ_COUNTER_FIRST
#define LineGraph_WRITE_OBJ_COUNTER_FIRST 14L
#undef LineGraph_RESERVED_1
#define LineGraph_RESERVED_1 15L
#undef LineGraph_RESERVED_2
#define LineGraph_RESERVED_2 16L
#undef LineGraph_RESERVED_3
#define LineGraph_RESERVED_3 17L
#undef LineGraph_RESERVED_4
#define LineGraph_RESERVED_4 18L
#undef LineGraph_RESERVED_5
#define LineGraph_RESERVED_5 19L
#undef LineGraph_RESERVED_6
#define LineGraph_RESERVED_6 20L
#undef LineGraph_WRITE_OBJ_COUNTER_LAST
#define LineGraph_WRITE_OBJ_COUNTER_LAST 21L
#undef LineGraph_REQUEST_FOCUS_DISABLED
#define LineGraph_REQUEST_FOCUS_DISABLED 22L
/* Inaccessible static: class_00024javax_00024swing_00024JComponent_00024KeyboardState */
/* Inaccessible static: class_00024javax_00024swing_00024event_00024AncestorListener */
/* Inaccessible static: class_00024java_00024beans_00024VetoableChangeListener */
/* Inaccessible static: class_00024java_00024beans_00024PropertyChangeListener */
/*
 * Class:     LineGraph
 * Method:    callLoadBufferClient
 * Signature: ([DLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_LineGraph_callLoadBufferClient
  (JNIEnv *, jobject, jdoubleArray, jstring);

/*
 * Class:     LineGraph
 * Method:    callPredBufferClient
 * Signature: ([D[DLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_LineGraph_callPredBufferClient
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jstring);

/*
 * Class:     LineGraph
 * Method:    callMeasureBufferClient
 * Signature: ([DLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_LineGraph_callMeasureBufferClient
  (JNIEnv *, jobject, jdoubleArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
