/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LineGraph */

#ifndef _Included_LineGraph
#define _Included_LineGraph
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: LOCK */
#undef LineGraph_assert
#define LineGraph_assert 0L
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef LineGraph_TOP_ALIGNMENT
#define LineGraph_TOP_ALIGNMENT 0.0f
#undef LineGraph_CENTER_ALIGNMENT
#define LineGraph_CENTER_ALIGNMENT 0.5f
#undef LineGraph_BOTTOM_ALIGNMENT
#define LineGraph_BOTTOM_ALIGNMENT 1.0f
#undef LineGraph_LEFT_ALIGNMENT
#define LineGraph_LEFT_ALIGNMENT 0.0f
#undef LineGraph_RIGHT_ALIGNMENT
#define LineGraph_RIGHT_ALIGNMENT 1.0f
#undef LineGraph_serialVersionUID
#define LineGraph_serialVersionUID -7644114512714619750LL
#undef LineGraph_serialVersionUID
#define LineGraph_serialVersionUID 4613797578919906343LL
/* Inaccessible static: readObjectCallbacks */
#undef LineGraph_WHEN_FOCUSED
#define LineGraph_WHEN_FOCUSED 0L
#undef LineGraph_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
#define LineGraph_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT 1L
#undef LineGraph_WHEN_IN_FOCUSED_WINDOW
#define LineGraph_WHEN_IN_FOCUSED_WINDOW 2L
#undef LineGraph_UNDEFINED_CONDITION
#define LineGraph_UNDEFINED_CONDITION -1L
#undef LineGraph_REQUEST_FOCUS_DISABLED
#define LineGraph_REQUEST_FOCUS_DISABLED 0L
#undef LineGraph_IS_DOUBLE_BUFFERED
#define LineGraph_IS_DOUBLE_BUFFERED 1L
#undef LineGraph_ANCESTOR_USING_BUFFER
#define LineGraph_ANCESTOR_USING_BUFFER 2L
#undef LineGraph_IS_PAINTING_TILE
#define LineGraph_IS_PAINTING_TILE 3L
#undef LineGraph_HAS_FOCUS
#define LineGraph_HAS_FOCUS 4L
#undef LineGraph_IS_OPAQUE
#define LineGraph_IS_OPAQUE 5L
#undef LineGraph_IS_PRINTING
#define LineGraph_IS_PRINTING 12L
#undef LineGraph_IS_PRINTING_ALL
#define LineGraph_IS_PRINTING_ALL 13L
/* Inaccessible static: class_00024javax_00024swing_00024JComponent_00024KeyboardState */
/* Inaccessible static: defaultLayout */
/*
 * Class:     LineGraph
 * Method:    callLoadBufferClient
 * Signature: ([DLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_LineGraph_callLoadBufferClient
  (JNIEnv *, jobject, jdoubleArray, jstring);

/*
 * Class:     LineGraph
 * Method:    callMeasureBufferClient
 * Signature: ([DLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_LineGraph_callMeasureBufferClient
  (JNIEnv *, jobject, jdoubleArray, jstring);

/*
 * Class:     LineGraph
 * Method:    callPredBufferClient
 * Signature: ([D[DLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_LineGraph_callPredBufferClient
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
